# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Project
version=1.0.1
group=org.dyvinia
java_version=25

# Common
mod_name=Explosion Control & Rebalance
mod_author=Dyvinia
mod_id=explosionrebalance
license=MIT
credits=
description=Server-side mod that gives you configurable control over explosions by allowing you to toggle griefing, add extra knockback, and/or modify damage for each source.

# Minecraft
minecraft_version=26.1
minecraft_version_fabric_range=>=26.1 <26.2
minecraft_version_neo_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# Dependencies
fc_api_port_version=26.1.4
